name: usher

channels:
  - https://prefix.dev/conda-forge
  - https://prefix.dev/bioconda
  - nodefaults

dependencies:
  - snakemake
  - numpy
  - matplotlib
  - notebook
  - ipywidgets
  - snakemake
  - git-lfs
  - gh
  - pandas
  - xlrd
  - seaborn
  - scipy
  - statsmodels
  - usher
  - nextclade
  - ucsc-fatovcf
  - biopython
  - pip
  - pip:
    - taxoniumtools
