# Configuration for flu-usher pipeline

# General settings
threads: 10

# Types and segments to analyze
subtypes:
  - "H3N2"
  # - "H7N9"
segments:
  - "HA"
  # - "NA"

# Reference accession numbers for each type-segment combination
references:
  "H3N2_HA": "NC_007366.1"

  "H7N9_HA": "NC_026425.1"
  "H7N9_NA": "NC_026429.1"

# Parameters for sequence curation
max_frac_gaps: 0.05
max_frac_ambig: 0.01