# Configuration for flu-usher pipeline

# General settings
threads: 10

# Types and segments to analyze
types:
  - "H7N9"
segments:
  - "HA"

# Parameters for curation
max_frac_gaps: 0.05
max_frac_ambig: 0.01

# Gene-specific parameters
gene_params:
  HA:
    start: 1
    end: 1683